test:
  nee4j:
    NEO4J_URI: "bolt://10.10.204.24:7687"
    NEO4J_USER: "neo4j"
    NEO4J_PASSWORD: "fengjr"
prod:
  nee4j:
    NEO4J_URI: "bolt://10.10.204.24:7687"
    NEO4J_USER: "neo4j"
    NEO4J_PASSWORD: "fengjr"