CREATE TABLE `assets_repay_plan` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `user_id` varchar(36) NOT NULL COMMENT '用户id',
  `loan_id` varchar(36) NOT NULL COMMENT '标的id',
  `periods_no` int(11) NOT NULL COMMENT '当前期数',
  `due_total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期应还总额',
  `due_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期应还本金',
  `due_interest_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期应还利息',
  `due_service_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应还服务费',
  `due_guarantee_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应还担保管理费',
  `due_brokerage_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应还居间服务费',
  `due_caution_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应还保证金',
  `due_penalty_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '应还罚息',
  `due_time` date NOT NULL COMMENT '本期应还时间',
  `penalty_date` date DEFAULT NULL COMMENT '罚息计算日期',
  `fact_total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期实际还款金额',
  `fact_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还本金',
  `fact_interest_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还利息',
  `fact_service_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还服务费',
  `fact_guarantee_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还担保管理费',
  `fact_brokerage_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还居间服务费',
  `fact_caution_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还保证金',
  `fact_penalty_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还罚息',
  `fact_advance_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '提前还款违约金',
  `real_total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期实际充值金额',
  `real_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实充本金',
  `real_interest_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实充值利息',
  `real_service_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实充值服务费',
  `real_guarantee_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实充值担保管理费',
  `real_brokerage_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还居间服务费',
  `real_caution_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '真实还保证金',
  `real_penalty_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '实还罚息',
  `real_advance_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '提前还款违约金',
  `guarantee_repay_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '还款代偿金额',
  `remain_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '剩余本金',
  `reduction_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免总金额（冲销+实还）',
  `reduce_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免本金',
  `reduce_interest_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免利息',
  `reduce_service_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免服务费',
  `reduce_guarantee_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免担保管理费',
  `reduce_brokerage_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免居间服务费',
  `reduce_caution_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免保证金',
  `reduce_penalty_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免罚息',
  `reduce_advance_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免提前还款违约金',
  `reduce_guarantee_repay_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '减免代偿金额',
  `subsidy_total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '本期补偿总金额',
  `subsidy_capital_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿本金',
  `subsidy_interest_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿利息',
  `subsidy_service_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿服务费',
  `subsidy_guarantee_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿担保管理费',
  `subsidy_brokerage_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿居间服务费',
  `subsidy_caution_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿保证金',
  `subsidy_penalty_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿罚息',
  `subsidy_advance_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿提前还款违约金',
  `subsidy_guarantee_repay_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '补偿代偿金额',
  `plan_start_time` datetime NOT NULL COMMENT '还款计划开始生效时间',
  `fact_time` datetime DEFAULT NULL COMMENT '本期实际还款时间',
  `plan_repay_time` datetime NOT NULL COMMENT '计划支付划扣时间',
  `repay_status` varchar(20) NOT NULL COMMENT '支付还款状态',
  `plan_status` varchar(21) NOT NULL COMMENT '还款计划状态',
  `invest_plan_status` varchar(21) NOT NULL COMMENT '投资端还款状态',
  `pay_msg` varchar(500) DEFAULT NULL COMMENT '支付结果描述',
  `origin_user` varchar(36) DEFAULT NULL COMMENT '发起方 system系统自动  user用户',
  `repay_result_msg` varchar(500) DEFAULT NULL COMMENT '扣款失败原因',
  `guarantee_status` varchar(45) NOT NULL COMMENT '担保状态',
  `guarantee_compensatory_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '担保代偿金额',
  `guarantee_type` varchar(45) DEFAULT NULL COMMENT '担保类型',
  `guarantee_id` varchar(45) DEFAULT NULL COMMENT '担保机构ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_loan_periods` (`loan_id`,`periods_no`),
  KEY `idx_user` (`user_id`),
  KEY `idx_penaltydate` (`penalty_date`),
  KEY `idx_due_time` (`due_time`),
  KEY `index_ct` (`create_time`),
  KEY `idx_periods_no` (`periods_no`) USING BTREE,
  KEY `idx_gId_gType_gStatus` (`guarantee_id`,`guarantee_type`,`guarantee_status`) USING BTREE,
  KEY `idx_pstatus_rStatus_penaltydate` (`plan_status`,`repay_status`,`penalty_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='还款计划'