dev:
  grpc:
    host: 10.10.204.10:9000
  model:
    max_num_actions: 200
    test_rollouts: 20
    LSTM_layers: 2
    data_input_dir: "D:\Program Files\pythonwork\DeliberatePractice\machine_learning\standard_online_project\datasets\data_preprocessed\raw_data_72138"
    base_output_dir: "output/raw_data_72138"
    path_length: 4
    hidden_size: 50
    embedding_size: 50
    batch_size: 256
    use_entity_embeddings: True
    model_name: "minerva"
    model_signature: "minerva"
test:
  grpc:
    host: 10.10.204.10:9000
  model:
    max_num_actions: 200
    test_rollouts: 20
    LSTM_layers: 2
    data_input_dir: "datasets/data_preprocessed/raw_data_72138"
    base_output_dir: "output/raw_data_72138"
    path_length: 4
    hidden_size: 50
    embedding_size: 50
    batch_size: 256
    use_entity_embeddings: True
    model_name: "minerva"
    model_signature: "minerva"
prod:
  grpc:
    host: 10.10.204.10:9000
  model:
    max_num_actions: 200
    test_rollouts: 20
    LSTM_layers: 2
    data_input_dir: "datasets/data_preprocessed/raw_data_72138"
    base_output_dir: "output/raw_data_72138"
    path_length: 4
    hidden_size: 50
    embedding_size: 50
    batch_size: 256
    use_entity_embeddings: True
    model_name: "minerva"
    model_signature: "minerva"