version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    detail:
        format: "[%(asctime)s]%(levelname)s:%(filename)s.%(funcName)s:%(lineno)d %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detail
        stream: ext://sys.stdout

    info_test_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detail
        filename: ./logs/out.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    info_prod_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detail
        filename: ./logs/out.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: detail
        filename: ./logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    test_log:
        level: WARN
        handlers: [console,info_test_file_handler]
        propagate: no
    prod_log:
        level: INFO
        handlers: [info_prod_file_handler]
        propagate: no
root:
    level: INFO
    handlers: [console, info_test_file_handler, error_file_handler]